### ISSUE TITLE
pod 搜索不到

### ISSUE THREAD

**Issue by usbwc** [shunFSKi/FSScrollContentView#1]
$ pod --version
1.3.0.beta.2

# wang @ localhost in ~/Documents/企友云仓 [17:51:02] 
$ pod search FSScrollContentView
[!] Unable to find a pod with name, author, summary, or description matching `FSScrollContentView`

**Comment by shunFSKi** [comment]
1.pod setup
2.pod search FSScrollContentView
```
-> FSScrollContentView (1.0.7)
   titleView pageView linkage.
   pod 'FSScrollContentView', '~> 1.0.7'
   - Homepage: https://github.com/shunFSKi/FSScrollContentView
   - Source:   https://github.com/shunFSKi/FSScrollContentView.git
   - Versions: 1.0.7, 1.0.6, 1.0.5, 1.0.3, 1.0.2, 1.0.1 [master repo]
(END)

```
